@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR
skinparam linetype ortho

Package Model <<Rectangle>>{
Interface Model <<Interface>>
Class Model
Class ModelManager

Package Patient {
Class Person
Class DOB
Class BloodType
Class NRIC
Class Name
Class Phone
Class PatientList
}

Package Appointment {
Class ApptList
Class Appt
Class Time
Class ApptDate
Class Reason
}

Package PatientRecord {
Class PatientRecordList
Class Pr
Class Allergies
Class Symptoms
Class Prescription
Class VisitDate
}
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model


ModelManager .up.|> Model

PatientList o--> "*" Person
Person *--> Name
Person *--> Phone
Person *--> BloodType
Person *--> DOB
Person *--> NRIC
Person *-right-> "*" Appt

ApptList o--> "*" Appt
Appt *--> Time
Appt *--> ApptDate
Appt *--> Reason

PatientRecordList o--> "*" Pr
Pr *--> Allergies
Pr *--> Symptoms
Pr *--> Prescription
Pr *--> VisitDate

Person *-left-> "*" Pr

Patient -up-> ModelManager
Appointment -up-> ModelManager
PatientRecord -up-> ModelManager

Name -[hidden]right-> Phone
Phone -[hidden]right-> DOB
DOB -[hidden]right-> BloodType

@enduml
