!define ARROW #101086
!define MAIN #ff0033
!define COMMAND #0059ff
!define PARSER #ff6969
!define PATIENT #02c46a
!define MEDICAL #52539e
!define APPOINTMENT #7d4d8a
!define TEXTUI #ff6969
!define STORAGE #ff6969

!define USER_COLOR #000000

skinparam BackgroundColor #FFFFFFF

skinparam Shadowing false

skinparam Class {
    FontColor #FFFFFF
    BorderThickness 1
    BorderColor #FFFFFF
    StereotypeFontColor #FFFFFF
    FontName Arial
}

skinparam Actor {
    BorderColor USER_COLOR
    Color USER_COLOR
    FontName Arial
}

skinparam Sequence {
    MessageAlign center
    BoxFontSize 15
    BoxPadding 0
    BoxFontColor #FFFFFF
    FontName Arial
}

skinparam Participant {
    FontColor #FFFFFFF
    Padding 20
}

skinparam MinClassWidth 50
skinparam ParticipantPadding 10
skinparam Shadowing false
skinparam DefaultTextAlignment center
skinparam packageStyle Rectangle

hide footbox
hide members
hide circle
