= SHOCO v2.1 - User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:xrefstyle: full
:repoURL: https://github.com/AY1920S2-CS2113T-T13-1/tp/tree/master

By: `Team SHOCOTech`      Since: `Mar 2020`


// @@author kokjoon97

== Introduction

Have you ever encountered the problem of having to make multiple trips to the supermarket because you forgot to get something important?
Have you ever gone to the supermarket just to realise you do not have enough cash on you?

If these problems sound familiar to you, fret not!
With SHOCO, such troubles are now a thing of the past.

SHOCO is a command-line interface (CLI) application that allows you to  manage and plan your shopping list and budget.
With better organisation and also a budget tracker, we are here to enhance your grocery-shopping experience and make the woes of grocery shopping disappear.
&nbsp;

+++<b>+++<<shoco-v20---user-guide,&#129053;
back to top>>+++</b>+++

== Quick Start

. Ensure that you have Java 11 or above installed.
. Download the latest version of `SHOCO` from https://github.com/AY1920S2-CS2113T-T13-1/tp/releases[here].
. Open the command prompt in the directory of the executable and type in the following command: `java -jar SHOCO.jar`
. You are now all set to plan your shopping list!
&nbsp;
// @@author

+++<b>+++<<shoco-v20---user-guide,&#129053;
back to top>>+++</b>+++

== Features

[discrete]
==== Command Format

* Please note the words in UPPER_CASE are the parameters that you can supply
 ** e.g.
in `ADD i/DESCRIPTION`, `DESCRIPTION` is a parameter which can be used as `ADD i/apple`.
* Items in square brackets are _optional_ and you can omit them.
 ** e.g `EDIT 1 [i/DESCRIPTION] [p/PRICE] [q/QUANTITY]` can be used as `EDIT 1 i/apple p/4.00` or as `EDIT 1 i/apple`.
// @@author kokjoon97
* All command words are case-sensitive and you should always use uppercase.
 ** e.g `ADD` in `ADD i/DESCRIPTION` consists of only uppercase letters.
* You can supply parameters for the `ADD` and `EDIT` command, namely `DESCRIPTION`, `QUANTITY` and `PRICE`, in any order.
 ** e.g `ADD i/apple q/5` *AND* `ADD q/5 i/apple` should both produce the same result.
* The keyword for the `FIND` command is case-insensitive.
 ** e.g If you have an item named "apple" in the list, both `FIND APPLE` *AND* `FIND apple` will display this entry to the user.
// @@author
&nbsp;

+++<b>+++<<shoco-v20---user-guide,&#129053;
back to top>>+++</b>+++

'''

// tag::Add[]
=== Adding an item: `ADD`

Add the specified item in the shopping list.

Format: `ADD i/DESCRIPTION [p/PRICE] [q/QUANTITY]`

* The `DESCRIPTION` must exist.
* The `[QUANTITY]` must be a *positive integer*.
_e.g 1, 2, 3 .._
* The `[PRICE]` must be in *numerical* form (decimal form accepted).
* `[PRICE]` and `[QUANTITY]` are optional values, user can choose to provide the  respective values or omit them.
The system will set the price and quantity to  the default values `0.0` and `1`
* note that you can rearrange the delimiters (more will shown in the example.)

Example of usage:

. `ADD i/potato p/5.00 q/3` *OR* `ADD p/5.00 q/3 i/potato`
 ** Add the description, price and quantity of this item in the shopping list
. `ADD i/potato chips p/5.00`  *OR*  `ADD i/potato chips q/2` *OR* `ADD p/5.00 i/potato chips`  *OR* `ADD q/5 i/potato chips`
 ** Add the description and price /  description and quantity /  of the item in the shopping list
. `ADD i/potato chips`
 ** Add only description of the item in the shopping list

&nbsp;

// end::Add[]

+++<b>+++<<shoco-v20---user-guide,&#129053;
back to top>>+++</b>+++
// @@author trishaangelica

'''

// tag::Edit[]
=== Editing an item: `EDIT`

Edits the specified item in the shopping list.

Format: `EDIT INDEX [i/DESCRIPTION] [p/PRICE] [q/QUANTITY]`

* Edits the item at the specified `INDEX`.
The `INDEX` refers to the index number  shown in the displayed shopping list.
* The `INDEX` and `[QUANTITY]` must be a *positive integer*.
_e.g 1, 2, 3 .._
* The `[PRICE]` must be in *positive numerical* form (decimal form accepted).
* *At least one* of the three parameters (description/price/quantity) must be present in the command.
* i/, p/, q/ delimiters can be in _any_ order.
e.g `i/..
p/..
q/..` or `q/..
i/..
p/..`.

Examples of usage:

. `EDIT 3 i/potato p/5.00 q/3`
 ** Edits the description, price and quantity of the 3rd item in the shopping list
. `EDIT 3 i/potato chips p/5.00`  *OR*  `EDIT 3 i/potato chips q/2`  *OR*  `EDIT 3 p/5.00 q/2`
 ** Edits the description and price /  description and quantity /  price and quantity of the   3rd item in the shopping list
. `EDIT 3 i/potato chips` *OR* `EDIT 3 p/5.00` *OR* `EDIT 3 q/2`
 ** Edits only description / only price / only quantity of the 3rd item in the shopping list

&nbsp;

// end::Edit[]

+++<b>+++<<shoco-v20---user-guide,&#129053;
back to top>>+++</b>+++
// @@author

'''


// @@author kokjoon97
// tag::Delete[]

=== Deleting an item: `DEL`

Removes an item from the list at the specified index.

Format: `DEL INDEX`

* The `INDEX` should be an integer.
* The `INDEX` should not be out of bounds of the shopping list.

Example of usage:

`DEL 3`
// @@author
// end::Delete[]

&nbsp;


+++<b>+++<<shoco-v20---user-guide,&#129053;
back to top>>+++</b>+++

'''

// tag::Clear[]
=== Clearing the list: `CLEAR`

Clears all items in the shopping list.
Automatically resets remaining budget to the user's set budget.

Format: `CLEAR`
// end::Clear[]

&nbsp;

+++<b>+++<<shoco-v20---user-guide,&#129053;
back to top>>+++</b>+++

'''
// tag::Mark[]
=== Marking an item as bought: `MARK`

Marks an item from the list at the specified index as bought.

Format: `MARK INDEX`

* The `INDEX` should be an integer.
* The `INDEX` should not be out of bounds of the shopping list.

Example of the usage:

`MARK 5`
// end::Mark[]

&nbsp;

+++<b>+++<<shoco-v20---user-guide,&#129053;
back to top>>+++</b>+++

'''

// tag::Unmark[]
=== Un-marking a marked item: `UNMARK`

Un-marks a marked-as-bought item from the list at the specified index.

Format: `UNMARK INDEX`

* The `INDEX` should be an integer
* The `INDEX` should not be out of bounds of the shopping list.

Example of the usage:

`UNMARK 3`
// end::Unmark[]

&nbsp;

+++<b>+++<<shoco-v20---user-guide,&#129053;
back to top>>+++</b>+++

'''

// tag::Display[]
=== Displaying list and budget details: `DISPLAY`

Shows the shopping list, budget, cost of the items and the remaining budget.

Format: `DISPLAY`
// end::Display[]

&nbsp;

+++<b>+++<<shoco-v20---user-guide,&#129053;
back to top>>+++</b>+++

'''

// @@author kokjoon97
// tag::SetBudget[]
=== Setting a budget: `SET`

Sets a budget for the user.

Format: `SET b/AMOUNT`

* The `AMOUNT` can be any decimal number that is between 0 to 5000.
* The `b/` substring should be present in the command.

Example of usage:

`SET b/3.00`
// @@author
// end::SetBudget[]

&nbsp;

+++<b>+++<<shoco-v20---user-guide,&#129053;
back to top>>+++</b>+++

'''
// tag::ResetBudget[]
=== Resetting a budget: `RES`

Resets te budget to be 0.00 for the user.

Format: `RES`
// end::ResetBudget[]

&nbsp;

+++<b>+++<<shoco-v20---user-guide,&#129053;
back to top>>+++</b>+++

'''

// @@author kokjoon97
// tag::Find[]
=== Finding an item: `FIND`

Filters the shopping list according to a keyword specified by the user.

Format: `FIND KEYWORD`

* The `KEYWORD` can be any character or string.
* The `KEYWORD` field should not be left empty.

Example of usage:

`FIND apple`
// @@author
// end::Find[]

&nbsp;

+++<b>+++<<shoco-v20---user-guide,&#129053;
back to top>>+++</b>+++

'''
// tag::Help[]
=== Viewing help: `HELP`

Shows the available commands and how they are to be used.

Format: `HELP`
// end::Help[]

&nbsp;

+++<b>+++<<shoco-v20---user-guide,&#129053;
back to top>>+++</b>+++

'''

// tag::Exit[]
=== Exiting the program: `BYE`

Exits the program.

Format: `BYE`
// end::Exit[]

&nbsp;

+++<b>+++<<shoco-v20---user-guide,&#129053;
back to top>>+++</b>+++

'''

&nbsp;
// @@author kokjoon97

== Additional information

=== 1. Loading and saving your shopping list

All your shopping list and budget data are saved to JSON files after you exit the application.
This data is also retrieved from the same JSON files the next time you boot up Shoco.
No further action is required from you as this is an automatic process.

=== 2. Automated budget tracker

When the total cost of the items in your shopping list exceeds the stored budget amount, a message will be displayed which states by how much you have overrun your current budget.
This message will only stop appearing when you increase your budget amount sufficiently or remove enough items from your list to keep within your budget.
// @@author

&nbsp;

+++<b>+++<<shoco-v20---user-guide,&#129053;
back to top>>+++</b>+++

&nbsp;

== FAQ

*Q*: How do I transfer my data to another computer?

*A*: Simply transfer the JSON files that contain your SHOCO data onto the new computer and place them in the folder that contains the SHOCO app.
If the folder already has the JSON files, replace them.

// @@author kokjoon97

*Q*: Is it possible to restore a list that I have deleted?

*A*: Unfortunately, we are still working on this feature and there is no such functionality at this point in time.
It is however, possible to manually backup the `shoppinglist.json` file from time to time so that if you unintentionally cleared your list, you can always replace the empty `shoppinglist.json` file with your backed up version.

// @@author

&nbsp;

+++<b>+++<<shoco-v20---user-guide,&#129053;
back to top>>+++</b>+++

&nbsp;

== Command Summary

* Add item `ADD i/DESCRIPTION [p/PRICE] [q/QUANTITY]`
* Edit item `EDIT INDEX [i/DESCRIPTION] [p/PRICE] [q/QUANTITY]`
* Delete item `DEL INDEX`
* Clear list `CLEAR`
* Mark item `MARK INDEX`
* Un-mark item `UNMARK INDEX`
* Display list and budget details `DISPLAY`
* Set budget `SET b/AMOUNT`
* Reset budget `RES`
* Find item `FIND KEYWORD`
* View help `HELP`
* Exit program `BYE`

&nbsp;

+++<b>+++<<shoco-v20---user-guide,&#129053;
back to top>>+++</b>+++
